# Generated by Django 5.0.6 on 2024-06-03 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 3, 16, 25, 14, 514086)),
            preserve_default=False,
        ),
    ]
